version: '3.8'


services:
  docker-api:
    container_name: web-api
    image: vafelka/windowapi:v1.0 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:80"  
    depends_on:
      - docker-sqlserver    
  docker-sqlserver:
    container_name: mssql-database
    image: vafelka/mssql:v1.0
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AXProduct2024
    ports:
      - "1401:1433"