
version: '3.8'

services:
  docker-api:
    container_name: web-api
    image: windowapi:latest
    ports:
      - "8081:80"
    depends_on:
      - docker-sqlserver    
  docker-sqlserver:
    container_name: mssql-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AXProduct2024
    ports:
      - "1401:1433"